name: asi-ml

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - ipykernel
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - seaborn
  - pandera
  - pip

  - pip:
      - black
      - kedro
      - kedro-datasets[pandas]
      - kedro-datasets[tracking]==2.*
      - kedro-viz
      - pre-commit
      - pytest
      - ruff
      - wandb
