target: pct_pos_total

clean:
  threshold_missing: 0.3
  bin_flag_cols:
    - website
    - support_url
    - detailed_description
    - about_the_game
    - short_description
    - header_image
    - screenshots
    - movies
  platform_cols:
    - windows
    - mac
    - linux
  drop_cols:
    - num_reviews_recent
    - pct_pos_recent
    - publishers
    - developers
    - packages
    - estimated_owners
  mlb_cols:
    - genres
    - categories
    - tags
    - supported_languages
    - full_audio_languages
  top_n_labels: 50

split:
  test_size: 0.2
  random_state: 42

model:
  random_state: 42
  n_estimators: 200
  n_jobs: -1
