target: pct_pos_total

clean:
  threshold_missing: 0.3
  bin_flag_cols:
    - website
    - support_url
    - detailed_description
    - about_the_game
    - short_description
    - header_image
    - screenshots
    - movies
  platform_cols:
    - windows
    - mac
    - linux
  drop_cols:
    - num_reviews_recent
    - pct_pos_recent
    - publishers
    - developers
    - packages
    - estimated_owners
    - name
    - reviews
    - metacritic_url
    - support_email
    - notes
  mlb_cols:
    - genres
    - categories
    - tags
    - supported_languages
    - full_audio_languages
  top_n_labels: 50

random_state: 42

split:
  test_size: 0.2
  random_state: ${random_state}

model:
  n_estimators: 200
  n_jobs: -1
  random_state: ${random_state}

autogluon:
  time_limit: 30
  presets: "medium_quality_faster_train"
  problem_type: "regression"
  label: ${target}
  eval_metric: "rmse"
  random_state: ${random_state}

#autogluon:
#  time_limit: 60
#  presets: "medium_quality"
#  problem_type: "regression"
#  label: ${target}
#  eval_metric: "rmse"
#  random_state: ${random_state}

#autogluon:
#  time_limit: 120
#  presets: "high_quality_fast_inference_only_refit"
#  problem_type: "regression"
#  label: ${target}
#  eval_metric: "rmse"
#  random_state: ${random_state}
