target: pct_pos_total

clean:
  threshold_missing: 0.3
  bin_flag_cols:
    - website
    - support_url
    - detailed_description
    - about_the_game
    - short_description
    - header_image
    - screenshots
    - movies
  platform_cols:
    - windows
    - mac
    - linux
  drop_cols:
    - num_reviews_recent
    - pct_pos_recent
    - publishers
    - developers
    - packages
    - estimated_owners
    - name
    - reviews
    - metacritic_url
    - support_email
    - notes
  mlb_cols:
    - genres
    - categories
    - tags
    - supported_languages
    - full_audio_languages
  top_n_labels: 50

random_state: 42

split:
  test_size: 0.2

model:
  n_estimators: 200
  n_jobs: -1

autogluon:
  time_limit: 30
  problem_type: "regression"
  label: pct_pos_total
  eval_metric: "rmse"
  random_state: 42

selection:
  primary_metric: rmse
  tie_breaker: inference_time_s   # metryka remis
  higher_is_better: false         # dla rmse false
  enable_wandb: true              # pozwala wyłączyć logowanie W&B w testach
  raw_dataset_path: data/01_raw/sample_100.csv  # do wersjonowania danych
